In [4]:
import pandas as pd

# ini load dataset
df= pd.read_csv("food_coded.csv")

# ini baca 5 paling atas, buat mastiin datanya jalan
df.head()

,GPA,Gender,breakfast,calories_chicken,calories_day,calories_scone,coffee,comfort_food,comfort_food_reasons,comfort_food_reasons_coded,...,soup,sports,thai_food,tortilla_calories,turkey_calories,type_sports,veggies_day,vitamins,waffle_calories,weight
0,2.4,2,1,430,NaN,315.0,1,none,we dont have comfort,9.0,...,1.0,1.0,1,1165.0,345,car racing,5,1,1315,187
1,3.654,1,1,610,3.0,420.0,2,"chocolate, chips, ice cream","Stress, bored, anger",1.0,...,1.0,1.0,2,725.0,690,Basketball,4,2,900,155
2,3.3,1,1,720,4.0,420.0,2,"frozen yogurt, pizza, fast food","stress, sadness",1.0,...,1.0,2.0,5,1165.0,500,none,5,1,900,I'm not answering this.
3,3.2,1,1,430,3.0,420.0,2,"Pizza, Mac and cheese, ice cream",Boredom,2.0,...,1.0,2.0,5,725.0,690,NaN,3,1,1315,"Not sure, 240"
4,3.5,1,1,720,2.0,420.0,2,"Ice cream, chocolate, chips","Stress, boredom, cravings",1.0,...,1.0,1.0,4,940.0,500,Softball,4,2,760,190

In [6]:
# cek info dataset
df.info()

# saya cek ada beberapa yang kosong
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           123 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  106 non-null    float64
 5   calories_scone                124 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  124 non-null    object
 8   comfort_food_reasons          124 non-null    object
 9   comfort_food_reasons_coded    106 non-null    float64
 10  cook                          122 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       108 non-null    float64
 13  diet_current                  124 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         123 non-null    float64
 16  eating_changes                122 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    116 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      112 non-null    float64
 23  father_education              124 non-null    float64
 24  father_profession             122 non-null    object
 25  fav_cuisine                   123 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      123 non-null    float64
 28  food_childhood                124 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  124 non-null    object
 35  ideal_diet                    124 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        124 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                124 non-null    float64
 41  marital_status                124 non-null    float64
 42  meals_dinner_friend           122 non-null    object
 43  mother_education              122 non-null    float64
 44  mother_profession             123 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 124 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  124 non-null    float64
 50  self_perception_weight        124 non-null    float64
 51  soup                          124 non-null    float64
 52  sports                        123 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             124 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   104 non-null    object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        123 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

GPA                  2
Gender               0
breakfast            0
calories_chicken     0
calories_day        19
                    ..
type_sports         21
veggies_day          0
vitamins             0
waffle_calories      0
weight               2
Length: 61, dtype: int64

In [8]:
# Disini saya makesure lagi secara keseluruhan total missing values
missing_cols = df.columns[df.isnull().any()]
print(df[missing_cols].isnull().sum())

GPA                            2
calories_day                  19
calories_scone                 1
comfort_food                   1
comfort_food_reasons           1
comfort_food_reasons_coded    19
cook                           3
cuisine                       17
diet_current                   1
drink                          2
eating_changes                 3
employment                     9
exercise                      13
father_education               1
father_profession              3
fav_cuisine                    2
fav_food                       2
food_childhood                 1
healthy_meal                   1
ideal_diet                     1
income                         1
life_rewarding                 1
marital_status                 1
meals_dinner_friend            3
mother_education               3
mother_profession              2
on_off_campus                  1
persian_food                   1
self_perception_weight         1
soup                           1
sports                         2
tortilla_calories              1
type_sports                   21
weight                         2
dtype: int64

In [10]:
# disini saya cek missing value dalam bentuk persen
missing_percent = (df[missing_cols].isnull().sum() / len(df)) * 100
print(missing_percent)

GPA                            1.6
calories_day                  15.2
calories_scone                 0.8
comfort_food                   0.8
comfort_food_reasons           0.8
comfort_food_reasons_coded    15.2
cook                           2.4
cuisine                       13.6
diet_current                   0.8
drink                          1.6
eating_changes                 2.4
employment                     7.2
exercise                      10.4
father_education               0.8
father_profession              2.4
fav_cuisine                    1.6
fav_food                       1.6
food_childhood                 0.8
healthy_meal                   0.8
ideal_diet                     0.8
income                         0.8
life_rewarding                 0.8
marital_status                 0.8
meals_dinner_friend            2.4
mother_education               2.4
mother_profession              1.6
on_off_campus                  0.8
persian_food                   0.8
self_perception_weight         0.8
soup                           0.8
sports                         1.6
tortilla_calories              0.8
type_sports                   16.8
weight                         1.6
dtype: float64

In [13]:
# Imputasi data numerik dengan mean
num_cols = df.select_dtypes(include=['float64', 'int64']).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Imputasi data kategorikal dengan modus
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# memastikan sudah selsai masalahnya
print(df.isnull().sum().sum())

0

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 61 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   GPA                           125 non-null    object
 1   Gender                        125 non-null    int64
 2   breakfast                     125 non-null    int64
 3   calories_chicken              125 non-null    int64
 4   calories_day                  125 non-null    float64
 5   calories_scone                125 non-null    float64
 6   coffee                        125 non-null    int64
 7   comfort_food                  125 non-null    object
 8   comfort_food_reasons          125 non-null    object
 9   comfort_food_reasons_coded    125 non-null    float64
 10  cook                          125 non-null    float64
 11  comfort_food_reasons_coded.1  125 non-null    int64
 12  cuisine                       125 non-null    float64
 13  diet_current                  125 non-null    object
 14  diet_current_coded            125 non-null    int64
 15  drink                         125 non-null    float64
 16  eating_changes                125 non-null    object
 17  eating_changes_coded          125 non-null    int64
 18  eating_changes_coded1         125 non-null    int64
 19  eating_out                    125 non-null    int64
 20  employment                    125 non-null    float64
 21  ethnic_food                   125 non-null    int64
 22  exercise                      125 non-null    float64
 23  father_education              125 non-null    float64
 24  father_profession             125 non-null    object
 25  fav_cuisine                   125 non-null    object
 26  fav_cuisine_coded             125 non-null    int64
 27  fav_food                      125 non-null    float64
 28  food_childhood                125 non-null    object
 29  fries                         125 non-null    int64
 30  fruit_day                     125 non-null    int64
 31  grade_level                   125 non-null    int64
 32  greek_food                    125 non-null    int64
 33  healthy_feeling               125 non-null    int64
 34  healthy_meal                  125 non-null    object
 35  ideal_diet                    125 non-null    object
 36  ideal_diet_coded              125 non-null    int64
 37  income                        125 non-null    float64
 38  indian_food                   125 non-null    int64
 39  italian_food                  125 non-null    int64
 40  life_rewarding                125 non-null    float64
 41  marital_status                125 non-null    float64
 42  meals_dinner_friend           125 non-null    object
 43  mother_education              125 non-null    float64
 44  mother_profession             125 non-null    object
 45  nutritional_check             125 non-null    int64
 46  on_off_campus                 125 non-null    float64
 47  parents_cook                  125 non-null    int64
 48  pay_meal_out                  125 non-null    int64
 49  persian_food                  125 non-null    float64
 50  self_perception_weight        125 non-null    float64
 51  soup                          125 non-null    float64
 52  sports                        125 non-null    float64
 53  thai_food                     125 non-null    int64
 54  tortilla_calories             125 non-null    float64
 55  turkey_calories               125 non-null    int64
 56  type_sports                   125 non-null    object
 57  veggies_day                   125 non-null    int64
 58  vitamins                      125 non-null    int64
 59  waffle_calories               125 non-null    int64
 60  weight                        125 non-null    object
dtypes: float64(20), int64(27), object(14)
memory usage: 59.7+ KB

In [22]:
# Ubah kolom numerik yang masih object ke float, yaitu GPA
df['GPA'] = pd.to_numeric(df['GPA'], errors='coerce')
df['weight'] = pd.to_numeric(df['weight'], errors='coerce')

# MENGECEK hasilnya kembali
df[['GPA', 'weight']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GPA     122 non-null    float64
 1   weight  122 non-null    float64
dtypes: float64(2)
memory usage: 2.1 KB

In [23]:
# export ke csv dimana datanya udh clean
df.to_csv('food_coded_clean.csv', index=False)